# This workflow will install Python dependencies, run tests, run linting, and test building docs
name: Codestyle and Linting

on:
  pull_request:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 black
    - name: Lint with Black
      run: |
        black --check --diff src
    - name: flake8
      run: |
        flake8 --count src

