# This workflow will install Python dependencies, run tests, run linting, and test building docs
name: Testing

on:
  pull_request:
    branches:
      - main
  workflow_dispatch: # For on demand runs
  schedule:
    - cron: 0 0 * * * # Scheduled run every day at midnight
jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest pytest-astropy pytest-cov
        python -m pip install -r requirements.txt


