# This workflow will install Python dependencies, run tests, run linting, and test building docs
name: Testing

on:
  pull_request:
    branches:
      - main
  workflow_dispatch: # For on demand runs
  schedule:
    - cron: 0 0 * * * # Scheduled run every day at midnight
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Install CDF library on Ubuntu
      run: |
        wget https://sdc-aws-support.s3.amazonaws.com/cdf-binaries/latest.zip
        unzip latest.zip
        echo "CDF_LIB=cdf/lib" >> $GITHUB_ENV

    # Set up Python 3.10 to match the version of Python used in AWS Lambda
    - name: Set up Python 10
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest -s lambda_function/tests --cov=lambda_function/src --cov-report=html --log-cli-level=INFO

