# This workflow will install Python dependencies, run tests, run linting, and test building docs
name: Testing

on:
  pull_request:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest pytest-astropy pytest-cov
    - name: Run tests
      run: pytest --pyargs src --cov src
      env:
        PLATFORM: ${{ matrix.platform }}

